name: Build Docker image and publish to DockerHub registry

on: [push]

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: vadimshpakovsky/hello-server:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
