name: Run unit tests
on: [ push ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out code
        uses: actions/checkout@v3
      - name: Install pipenv
        run: pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - name: Setup environment
        run: pipenv sync --dev
      - name: Run unit tests
        run: pipenv run pytest tests/
