name: Run unit tests

on: [ push ]

#jobs:
#  run-unit-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check-out code
#        uses: actions/checkout@v3
#
#      - name: Install pipenv
#        run: pipx install pipenv
#
#      - name: Setup Python
#        uses: actions/setup-python@v3
#        with:
#          python-version: '3.9'
#          cache: 'pipenv'
#
#      - name: Setup environment
#        run: pipenv sync --dev
#
#      - name: Run unit tests
#        run: pipenv run pytest tests/
#
#  run-docker-image-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check-out code
#        uses: actions/checkout@v3
#
#      - name: Build Docker image
#        run: docker build -t hello-server .
#
#      - name: Run Docker image
#        run: |
#          docker run -d -p 8080:8080 hello-server
#
#          # waiting app running
#          sleep 5
#
#      - name: Check server awailability
#        run: |
#          response_body=$(curl http://localhost:8080/hello)
#
#          if [[ $response_body != 'Hello, world!' ]] ; then
#            echo "Unexpected response: $response_body"
#            exit 1
#          fi
